apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      containers:
        - name: sensor
          image: argoproj/sensor:v0.13.0-rc
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      gatewayName: webhook-gateway
      eventName: example
  subscription:
    http:
      port: 9300
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: noisy-processor-
              spec:
                entrypoint: noisy
                arguments:
                  parameters:
                    - name: filterA
                      value: "5"
                    - name: filterB
                      value: "5"
                    - name: sVSp
                      value: "0.5"
                    - name: amount
                      value: "0.004"
                templates:
                  - name: noisy
                    serviceAccountName: argo-events-sa
                    inputs:
                      parameters:
                        - name: filterA
                        - name: filterB
                        - name: sVSp
                        - name: amount
                    container:
                      image: metalgearsolid/demo-blur-argo-logo:latest
                      command: [papermill]
                      imagePullPolicy: Always
                      env:
                        - name: AWS_ACCESS_KEY_ID
                          value: minio
                        - name: AWS_SECRET_ACCESS_KEY
                          value: minio123
                        - name: AWS_DEFAULT_REGION
                          value: us-east-1
                        - name: BOTO3_ENDPOINT_URL
                          value: http://minio-service.argo-events.svc:9000
                      args:
                        - "noise.ipynb"
                        - "s3://output/noisy-out.ipynb"
                        - "-p"
                        - "filterA"
                        - "{{inputs.parameters.filterA}}"
                        - "-p"
                        - "filterB"
                        - "{{inputs.parameters.filterB}}"
                        - "-p"
                        - "sVSp"
                        - "{{inputs.parameters.sVSp}}"
                        - "-p"
                        - "amount"
                        - "{{inputs.parameters.amount}}"
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.filterA
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.filterB
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: test-dep
                dataKey: body.sVSp
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: test-dep
                dataKey: body.amount
              dest: spec.arguments.parameters.3.value
